create table _authentication (id integer not null, is_email_confirmed BOOL DEFAULT false, registered_time datetime(6), email varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table _authentication_role (authentication_id integer not null, role_id integer not null, primary key (authentication_id, role_id)) engine=InnoDB;
create table _authentication_seq (next_val bigint) engine=InnoDB;
insert into _authentication_seq values ( 1 );
create table _authentication_token (authentication_id integer not null, expiry_date datetime(6), id bigint not null, registered_time datetime(6), token varchar(255), primary key (id)) engine=InnoDB;
create table _authentication_token_seq (next_val bigint) engine=InnoDB;
insert into _authentication_token_seq values ( 1 );
create table _badge (buyer_id integer not null, id integer not null, created_time datetime(6), description varchar(255), image_source varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table _badge_seq (next_val bigint) engine=InnoDB;
insert into _badge_seq values ( 1 );
create table _badge_tag (badge_id integer not null, id integer not null, type tinyint check (type between 0 and 3), created_time datetime(6), title varchar(255), primary key (id)) engine=InnoDB;
create table _badge_tag_seq (next_val bigint) engine=InnoDB;
insert into _badge_tag_seq values ( 1 );
create table _buyers (authentication_id integer not null, birthday date, id integer not null, registered_time datetime(6), bio varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table _buyers_seq (next_val bigint) engine=InnoDB;
insert into _buyers_seq values ( 1 );
create table _cart (buyer_id integer not null, id integer not null, payment_method_id integer not null, shipping_address_id integer not null, created_time datetime(6), primary key (id)) engine=InnoDB;
create table _cart_item (amount integer not null, cart_id integer not null, id integer not null, product_id integer not null, created_time datetime(6), primary key (id)) engine=InnoDB;
create table _cart_item_seq (next_val bigint) engine=InnoDB;
insert into _cart_item_seq values ( 1 );
create table _cart_seq (next_val bigint) engine=InnoDB;
insert into _cart_seq values ( 1 );
create table _order (buyer_id integer not null, id integer not null, payment_method_id integer not null, shipping_address_id integer not null, created_time datetime(6), primary key (id)) engine=InnoDB;
create table _order_item (amount integer not null, id integer not null, order_id integer not null, product_id integer not null, created_time datetime(6), primary key (id)) engine=InnoDB;
create table _order_item_seq (next_val bigint) engine=InnoDB;
insert into _order_item_seq values ( 1 );
create table _order_seq (next_val bigint) engine=InnoDB;
insert into _order_seq values ( 1 );
create table _payment_methods (id integer not null, created_time datetime(6), title varchar(255), primary key (id)) engine=InnoDB;
create table _payment_methods_seq (next_val bigint) engine=InnoDB;
insert into _payment_methods_seq values ( 1 );
create table _product (expiration_date date, id integer not null, seller_id integer not null, created_time datetime(6), characteristics varchar(255), description varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table _product_review (buyer_id integer not null, id integer not null, product_id integer not null, rating integer not null, created_time datetime(6), comment varchar(255), primary key (id)) engine=InnoDB;
create table _product_review_seq (next_val bigint) engine=InnoDB;
insert into _product_review_seq values ( 1 );
create table _product_seq (next_val bigint) engine=InnoDB;
insert into _product_seq values ( 1 );
create table _roles (id integer not null, created_time datetime(6), name enum ('ADMIN','BUYER','MODERATOR','SELLER','USER'), primary key (id)) engine=InnoDB;
create table _roles_seq (next_val bigint) engine=InnoDB;
insert into _roles_seq values ( 1 );
create table _sellers (authentication_id integer not null, birthday date, id integer not null, registered_time datetime(6), bio varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table _sellers_seq (next_val bigint) engine=InnoDB;
insert into _sellers_seq values ( 1 );
create table _shipping_addresses (id integer not null, latitude float(53), longitude float(53), created_time datetime(6), city varchar(255), country varchar(255), postal_code varchar(255), state varchar(255), street_address varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table _shipping_addresses_seq (next_val bigint) engine=InnoDB;
insert into _shipping_addresses_seq values ( 1 );
create table _transparent_policy (id integer not null, created_time datetime(6), title varchar(255), type varchar(255), primary key (id)) engine=InnoDB;
create table _transparent_policy_seller (id integer not null, seller_id integer not null, transparent_policy_id integer not null, primary key (id, seller_id, transparent_policy_id)) engine=InnoDB;
create table _transparent_policy_seller_seq (next_val bigint) engine=InnoDB;
insert into _transparent_policy_seller_seq values ( 1 );
create table _transparent_policy_seq (next_val bigint) engine=InnoDB;
insert into _transparent_policy_seq values ( 1 );
alter table _authentication add constraint UK_q3hi1u99dl0vldawquw302hpa unique (email);
alter table _authentication_token add constraint UK_2y2t7lg09logmpsysk8imbo1r unique (authentication_id);
alter table _authentication_token add constraint UK_fx6ru820sw08xjufceif5pqgh unique (token);
alter table _buyers add constraint UK_51w0up1o848genfgrjyqqngys unique (authentication_id);
alter table _cart add constraint UK_fx76lm4psih0vp4obw8k5jwv0 unique (buyer_id);
alter table _sellers add constraint UK_2wjkiflylklw60345jicp2bek unique (authentication_id);
alter table _transparent_policy_seller add constraint uc_id unique (id);
alter table _authentication_role add constraint FKc5lx61l1hoongqyde2kntvwje foreign key (authentication_id) references _authentication (id);
alter table _authentication_role add constraint FK6myisy5bonv91ld4aj11c7ycg foreign key (role_id) references _roles (id);
alter table _authentication_token add constraint FKelnersk5fkswnaqge118slbqv foreign key (authentication_id) references _authentication (id) on delete cascade;
alter table _badge add constraint FK2j8qq3i2hc167ebjp98a4xkpv foreign key (buyer_id) references _buyers (id);
alter table _badge_tag add constraint FKr1dtlfpcu0fb8amfldg7852hh foreign key (badge_id) references _badge (id);
alter table _buyers add constraint FKrmfopl3g7okcpmfu79k4feotn foreign key (authentication_id) references _authentication (id) on delete cascade;
alter table _cart add constraint FKpwestf5h4eyrbouti5tvl0d5s foreign key (buyer_id) references _buyers (id);
alter table _cart add constraint FK7569s7nmyfxn4ntys3jdahdd3 foreign key (payment_method_id) references _payment_methods (id);
alter table _cart add constraint FKri9lerjcykbcj0dvfiy5jbo2v foreign key (shipping_address_id) references _shipping_addresses (id);
alter table _cart_item add constraint FKmkbtxtd5xkr59p1tdf9g3r0br foreign key (cart_id) references _cart (id);
alter table _cart_item add constraint FKq7a2ocg7i08wmmiqj16qrm2il foreign key (product_id) references _product (id);
alter table _order add constraint FK435eu2rx3g2y30l5rhj8u96xl foreign key (buyer_id) references _buyers (id);
alter table _order add constraint FK4f4vvk9r4aydqeg0m3o475xwx foreign key (payment_method_id) references _payment_methods (id);
alter table _order add constraint FKodsq6ce8pas8e375kdkm0d2i7 foreign key (shipping_address_id) references _shipping_addresses (id);
alter table _order_item add constraint FKkm6x6ueuqv4kgtiluwv49003v foreign key (order_id) references _order (id);
alter table _order_item add constraint FK3u4cex6olyf7tauwhqf2qxi0h foreign key (product_id) references _product (id);
alter table _product add constraint FKb5vbbavo9eakjcgfkvq39chwj foreign key (seller_id) references _sellers (id);
alter table _product_review add constraint FK6o4q1i9iy8s3xil26gawm3j0w foreign key (buyer_id) references _buyers (id);
alter table _product_review add constraint FK91549px9csqo5wodkd73skjlx foreign key (product_id) references _product (id);
alter table _sellers add constraint FKp2ktngvj9nk4qhgu062hjfje2 foreign key (authentication_id) references _authentication (id) on delete cascade;
alter table _transparent_policy_seller add constraint FKlbu3ahlljh74aver0e7x5v672 foreign key (seller_id) references _sellers (id);
alter table _transparent_policy_seller add constraint FKagy17kcphinaky03gg30e8695 foreign key (transparent_policy_id) references _transparent_policy (id);
