scrape_configs:
  - job_name: 'GreenShop'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 15s
    scheme: http
    enable_http2: false
    static_configs:
      - targets: ['greenshop-dev-service-1:8080']
        labels:
          application: 'My Spring Boot Application'
          