scrape_configs:
  - job_name: 'GreenShop'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['greenshop-dev_service_1:8080']
        labels:
          application: 'My Spring Boot Application'
          