version: '3'

services:
  spring:
    build:
        context: ../../service/Authorization/service
        dockerfile: ./dev.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
        context: ../../service/Authorization/db
        dockerfile: ./dev.Dockerfile
    command: --mysql-native-password=ON
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_HOST: localhost
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: db
        MYSQL_ADMIN: admin
        MYSQL_ADMIN_PASSWORD: admin
        MYSQL_PUBLIC_USER: public
        MYSQL_FLYWAY_USER: flyway
        MYSQL_FLYWAY_PASSWORD: flyway
    volumes:
      - db-dev:/var/lib/mysql
    deploy:
        resources:
            limits:
                cpus: 1 # Limit to 4 CPUs
                memory: 600M # Limit to 600MiB of memory
  db-backup:
    build:
        context: ../../service/Authorization/db
        dockerfile: ./mysql-backup.Dockerfile
    ports:
      - "3307:3307"
    volumes:
      - db-dev:/var/lib/mysql
    depends_on:
      - db
      
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    volumes:
      - minio-dev:/data
    command: ["server", "--console-address", ":9001", "/data"]

volumes:
  db-dev:
  minio-dev: 