create table _authentication (id integer not null, is_email_confirmed BOOL DEFAULT false, registered_time datetime(6), email varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table _authentication_seq (next_val bigint) engine=InnoDB;
insert into _authentication_seq values ( 1 );
create table _authentication_token (authentication_id integer not null, expiry_date datetime(6), id bigint not null, registered_time datetime(6), token varchar(255), primary key (id)) engine=InnoDB;
create table _authentication_token_seq (next_val bigint) engine=InnoDB;
insert into _authentication_token_seq values ( 1 );
create table _badge (id integer not null, created_time datetime(6), description varchar(255), image_source varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table _badge_seq (next_val bigint) engine=InnoDB;
insert into _badge_seq values ( 1 );
create table _buyers (authentication_id integer not null, birthday date, commission_percentage integer, id integer not null, registered_time datetime(6), bio varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table _buyers_seq (next_val bigint) engine=InnoDB;
insert into _buyers_seq values ( 1 );
create table _cart (buyer_id integer, id integer not null, payment_method_id integer, shipping_address_id integer, created_time datetime(6), primary key (id)) engine=InnoDB;
create table _cart_item (amount integer not null, cart_id integer not null, id integer not null, product_id integer not null, created_time datetime(6), primary key (id)) engine=InnoDB;
create table _cart_item_seq (next_val bigint) engine=InnoDB;
insert into _cart_item_seq values ( 1 );
create table _cart_seq (next_val bigint) engine=InnoDB;
insert into _cart_seq values ( 1 );
create table _category (id integer not null, created_time datetime(6), name varchar(255), primary key (id)) engine=InnoDB;
create table _category_seq (next_val bigint) engine=InnoDB;
insert into _category_seq values ( 1 );
create table _order (buyer_id integer not null, id integer not null, payment_method_id integer, shipping_address_id integer, created_time datetime(6), primary key (id)) engine=InnoDB;
create table _order_item (amount integer not null, commission_percentage integer, id integer not null, order_id integer not null, price decimal(38,2), product_id integer not null, created_time datetime(6), primary key (id)) engine=InnoDB;
create table _order_item_seq (next_val bigint) engine=InnoDB;
insert into _order_item_seq values ( 1 );
create table _order_seq (next_val bigint) engine=InnoDB;
insert into _order_seq values ( 1 );
create table _payment_methods (id integer not null, created_time datetime(6), title varchar(255), primary key (id)) engine=InnoDB;
create table _payment_methods_seq (next_val bigint) engine=InnoDB;
insert into _payment_methods_seq values ( 1 );
create table _product (expiration_date date, id integer not null, price decimal(38,2), seller_id integer not null, created_time datetime(6), characteristics varchar(255), description varchar(255), image_filename varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table _product_review (buyer_id integer not null, id integer not null, order_item_id integer not null, product_id integer not null, rating integer not null, created_time datetime(6), comment varchar(255), primary key (id)) engine=InnoDB;
create table _product_review_seq (next_val bigint) engine=InnoDB;
insert into _product_review_seq values ( 1 );
create table _product_seq (next_val bigint) engine=InnoDB;
insert into _product_seq values ( 1 );
create table _roles (id integer not null, created_time datetime(6), name enum ('ADMIN','BUYER','MODERATOR','SELLER','USER'), primary key (id)) engine=InnoDB;
create table _roles_seq (next_val bigint) engine=InnoDB;
insert into _roles_seq values ( 1 );
create table _sellers (authentication_id integer not null, birthday date, commission_percentage integer, id integer not null, registered_time datetime(6), bio varchar(255), name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
create table _sellers_seq (next_val bigint) engine=InnoDB;
insert into _sellers_seq values ( 1 );
create table _shipping_addresses (id integer not null, latitude float(53), longitude float(53), created_time datetime(6), city varchar(255), country varchar(255), postal_code varchar(255), state varchar(255), street_address varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table _shipping_addresses_seq (next_val bigint) engine=InnoDB;
insert into _shipping_addresses_seq values ( 1 );
create table _tag (id integer not null, created_time datetime(6), title varchar(255), type enum ('LIMITED','NEW','POPULAR','SALE'), primary key (id)) engine=InnoDB;
create table _tag_seq (next_val bigint) engine=InnoDB;
insert into _tag_seq values ( 1 );
create table _transparent_policy (id integer not null, value integer, created_time datetime(6), name enum ('AVAILABLE_PRODUCT_ORDERS','AVAILABLE_PRODUCT_ORDERS_BUYER','AVAILABLE_PRODUCT_ORDERS_DATE','AVAILABLE_PRODUCT_ORDERS_PRICE'), type varchar(255), primary key (id)) engine=InnoDB;
create table _transparent_policy_history (authentication_id integer not null, id integer not null, transparent_policy_id integer not null, created_time datetime(6), primary key (id)) engine=InnoDB;
create table _transparent_policy_history_seq (next_val bigint) engine=InnoDB;
insert into _transparent_policy_history_seq values ( 1 );
create table _transparent_policy_seq (next_val bigint) engine=InnoDB;
insert into _transparent_policy_seq values ( 1 );
create table authentication_role (authentication_id integer not null, role_id integer not null) engine=InnoDB;
create table authentication_transparent_policy (authentication_id integer not null, authentication_transparent_policy_id integer not null) engine=InnoDB;
create table badge_tag (badge_id integer not null, tag_id integer not null) engine=InnoDB;
create table buyer_badge (badge_id integer not null, buyer_id integer not null) engine=InnoDB;
create table order_item_buyer_transparent_policy (buyer_order_item_id integer not null, buyer_transparent_policy_id integer not null) engine=InnoDB;
create table order_item_seller_transparent_policy (seller_order_item_id integer not null, seller_transparent_policy_id integer not null) engine=InnoDB;
create table product_category (category_id integer not null, product_id integer not null) engine=InnoDB;
create table product_tag (product_id integer not null, tag_id integer not null) engine=InnoDB;
alter table _authentication add constraint UK_q3hi1u99dl0vldawquw302hpa unique (email);
alter table _authentication_token add constraint UK_2y2t7lg09logmpsysk8imbo1r unique (authentication_id);
alter table _authentication_token add constraint UK_fx6ru820sw08xjufceif5pqgh unique (token);
alter table _buyers add constraint UK_51w0up1o848genfgrjyqqngys unique (authentication_id);
alter table _cart add constraint UK_fx76lm4psih0vp4obw8k5jwv0 unique (buyer_id);
alter table _product_review add constraint UK_in8o2p9laedq8v8cg4kl8yxwg unique (order_item_id);
alter table _sellers add constraint UK_2wjkiflylklw60345jicp2bek unique (authentication_id);
alter table _authentication_token add constraint FKelnersk5fkswnaqge118slbqv foreign key (authentication_id) references _authentication (id);
alter table _buyers add constraint FKrmfopl3g7okcpmfu79k4feotn foreign key (authentication_id) references _authentication (id) on delete cascade;
alter table _cart add constraint FKpwestf5h4eyrbouti5tvl0d5s foreign key (buyer_id) references _buyers (id) on delete cascade;
alter table _cart add constraint FK7569s7nmyfxn4ntys3jdahdd3 foreign key (payment_method_id) references _payment_methods (id);
alter table _cart add constraint FKri9lerjcykbcj0dvfiy5jbo2v foreign key (shipping_address_id) references _shipping_addresses (id);
alter table _cart_item add constraint FKmkbtxtd5xkr59p1tdf9g3r0br foreign key (cart_id) references _cart (id) on delete cascade;
alter table _cart_item add constraint FKq7a2ocg7i08wmmiqj16qrm2il foreign key (product_id) references _product (id);
alter table _order add constraint FK435eu2rx3g2y30l5rhj8u96xl foreign key (buyer_id) references _buyers (id);
alter table _order add constraint FK4f4vvk9r4aydqeg0m3o475xwx foreign key (payment_method_id) references _payment_methods (id) on delete cascade;
alter table _order add constraint FKodsq6ce8pas8e375kdkm0d2i7 foreign key (shipping_address_id) references _shipping_addresses (id) on delete cascade;
alter table _order_item add constraint FKkm6x6ueuqv4kgtiluwv49003v foreign key (order_id) references _order (id) on delete cascade;
alter table _order_item add constraint FK3u4cex6olyf7tauwhqf2qxi0h foreign key (product_id) references _product (id) on delete cascade;
alter table _product add constraint FKb5vbbavo9eakjcgfkvq39chwj foreign key (seller_id) references _sellers (id) on delete cascade;
alter table _product_review add constraint FK6o4q1i9iy8s3xil26gawm3j0w foreign key (buyer_id) references _buyers (id) on delete cascade;
alter table _product_review add constraint FKnpefsg2nbtm7y9w4qqumif3ya foreign key (order_item_id) references _order_item (id) on delete cascade;
alter table _product_review add constraint FK91549px9csqo5wodkd73skjlx foreign key (product_id) references _product (id) on delete cascade;
alter table _sellers add constraint FKp2ktngvj9nk4qhgu062hjfje2 foreign key (authentication_id) references _authentication (id) on delete cascade;
alter table _transparent_policy_history add constraint FKc5vx26um0xal5yk0q3lpvv25d foreign key (authentication_id) references _authentication (id) on delete cascade;
alter table _transparent_policy_history add constraint FKa92c4ymxgj81ycyl1hxlnr4mo foreign key (transparent_policy_id) references _transparent_policy (id) on delete cascade;
alter table authentication_role add constraint FK3xq58x5a2dmqte9n69erwso56 foreign key (role_id) references _roles (id);
alter table authentication_role add constraint FKlmygagyqgxwcl36jw42ksknjj foreign key (authentication_id) references _authentication (id);
alter table authentication_transparent_policy add constraint FK9htm9a5n2l8s3tvjh8i7xwrg1 foreign key (authentication_transparent_policy_id) references _transparent_policy (id) on delete cascade;
alter table authentication_transparent_policy add constraint FKdrc0jg2mb92jkx3a9a881ugxh foreign key (authentication_id) references _authentication (id);
alter table badge_tag add constraint FKh52784deahccy7gon93h6b0qw foreign key (tag_id) references _tag (id) on delete cascade;
alter table badge_tag add constraint FKpuhke69rjxunduimku8hixoff foreign key (badge_id) references _badge (id);
alter table buyer_badge add constraint FKth30ngua537yy4p53ju5xxrll foreign key (badge_id) references _badge (id) on delete cascade;
alter table buyer_badge add constraint FKnn3i7dafcj72h7ialqcofq2bo foreign key (buyer_id) references _buyers (id);
alter table order_item_buyer_transparent_policy add constraint FKt3niwdcci21gn3vcuq1w8fyxu foreign key (buyer_transparent_policy_id) references _transparent_policy (id) on delete cascade;
alter table order_item_buyer_transparent_policy add constraint FKmsx5l89yrohwkjkbhfv83bc4a foreign key (buyer_order_item_id) references _order_item (id);
alter table order_item_seller_transparent_policy add constraint FKdgomemsnveapoymf504jsp6s foreign key (seller_transparent_policy_id) references _transparent_policy (id) on delete cascade;
alter table order_item_seller_transparent_policy add constraint FK34p47cxlbrsl792pwthcwdjvd foreign key (seller_order_item_id) references _order_item (id);
alter table product_category add constraint FK5hn33vnu1s0875sbo9ttp47h4 foreign key (category_id) references _category (id);
alter table product_category add constraint FKctkss89hotjhvlpo6xa6ldwk8 foreign key (product_id) references _product (id);
alter table product_tag add constraint FKne9uhd1a92ofyjunwaa2vqamu foreign key (tag_id) references _tag (id);
alter table product_tag add constraint FKtobm6b100r4qhgaoy5vhgbs28 foreign key (product_id) references _product (id) on delete cascade;
