alter table _authentication_token drop foreign key FKelnersk5fkswnaqge118slbqv;
alter table _buyers drop foreign key FKrmfopl3g7okcpmfu79k4feotn;
alter table _cart drop foreign key FKpwestf5h4eyrbouti5tvl0d5s;
alter table _cart drop foreign key FK7569s7nmyfxn4ntys3jdahdd3;
alter table _cart drop foreign key FKri9lerjcykbcj0dvfiy5jbo2v;
alter table _cart_item drop foreign key FKmkbtxtd5xkr59p1tdf9g3r0br;
alter table _cart_item drop foreign key FKq7a2ocg7i08wmmiqj16qrm2il;
alter table _order drop foreign key FK435eu2rx3g2y30l5rhj8u96xl;
alter table _order drop foreign key FK4f4vvk9r4aydqeg0m3o475xwx;
alter table _order drop foreign key FKodsq6ce8pas8e375kdkm0d2i7;
alter table _order_item drop foreign key FKkm6x6ueuqv4kgtiluwv49003v;
alter table _order_item drop foreign key FK3u4cex6olyf7tauwhqf2qxi0h;
alter table _product drop foreign key FKb5vbbavo9eakjcgfkvq39chwj;
alter table _product_review drop foreign key FK6o4q1i9iy8s3xil26gawm3j0w;
alter table _product_review drop foreign key FKnpefsg2nbtm7y9w4qqumif3ya;
alter table _product_review drop foreign key FK91549px9csqo5wodkd73skjlx;
alter table _sellers drop foreign key FKp2ktngvj9nk4qhgu062hjfje2;
alter table _transparent_policy_history drop foreign key FKc5vx26um0xal5yk0q3lpvv25d;
alter table _transparent_policy_history drop foreign key FKa92c4ymxgj81ycyl1hxlnr4mo;
alter table authentication_role drop foreign key FK3xq58x5a2dmqte9n69erwso56;
alter table authentication_role drop foreign key FKlmygagyqgxwcl36jw42ksknjj;
alter table authentication_transparent_policy drop foreign key FK9htm9a5n2l8s3tvjh8i7xwrg1;
alter table authentication_transparent_policy drop foreign key FKdrc0jg2mb92jkx3a9a881ugxh;
alter table badge_tag drop foreign key FKh52784deahccy7gon93h6b0qw;
alter table badge_tag drop foreign key FKpuhke69rjxunduimku8hixoff;
alter table buyer_badge drop foreign key FKth30ngua537yy4p53ju5xxrll;
alter table buyer_badge drop foreign key FKnn3i7dafcj72h7ialqcofq2bo;
alter table order_item_buyer_transparent_policy drop foreign key FKt3niwdcci21gn3vcuq1w8fyxu;
alter table order_item_buyer_transparent_policy drop foreign key FKmsx5l89yrohwkjkbhfv83bc4a;
alter table order_item_seller_transparent_policy drop foreign key FKdgomemsnveapoymf504jsp6s;
alter table order_item_seller_transparent_policy drop foreign key FK34p47cxlbrsl792pwthcwdjvd;
alter table product_category drop foreign key FK5hn33vnu1s0875sbo9ttp47h4;
alter table product_category drop foreign key FKctkss89hotjhvlpo6xa6ldwk8;
alter table product_tag drop foreign key FKne9uhd1a92ofyjunwaa2vqamu;
alter table product_tag drop foreign key FKtobm6b100r4qhgaoy5vhgbs28;
drop table if exists _authentication;
drop table if exists _authentication_seq;
drop table if exists _authentication_token;
drop table if exists _authentication_token_seq;
drop table if exists _badge;
drop table if exists _badge_seq;
drop table if exists _buyers;
drop table if exists _buyers_seq;
drop table if exists _cart;
drop table if exists _cart_item;
drop table if exists _cart_item_seq;
drop table if exists _cart_seq;
drop table if exists _category;
drop table if exists _category_seq;
drop table if exists _order;
drop table if exists _order_item;
drop table if exists _order_item_seq;
drop table if exists _order_seq;
drop table if exists _payment_methods;
drop table if exists _payment_methods_seq;
drop table if exists _product;
drop table if exists _product_review;
drop table if exists _product_review_seq;
drop table if exists _product_seq;
drop table if exists _roles;
drop table if exists _roles_seq;
drop table if exists _sellers;
drop table if exists _sellers_seq;
drop table if exists _shipping_addresses;
drop table if exists _shipping_addresses_seq;
drop table if exists _tag;
drop table if exists _tag_seq;
drop table if exists _transparent_policy;
drop table if exists _transparent_policy_history;
drop table if exists _transparent_policy_history_seq;
drop table if exists _transparent_policy_seq;
drop table if exists authentication_role;
drop table if exists authentication_transparent_policy;
drop table if exists badge_tag;
drop table if exists buyer_badge;
drop table if exists order_item_buyer_transparent_policy;
drop table if exists order_item_seller_transparent_policy;
drop table if exists product_category;
drop table if exists product_tag;
