name: Docker Compose Build and Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        # Checking compose version
      - name: Set up Docker Compose
        run: docker-compose --version
        continue-on-error: true

        # Specify the path to your directory containing the docker-compose.yml file.
      - name: Run Batch File Docker Compose Build and Run
        run: |
          ./docker/development.bat

        # Show the logs after starting the services.
      - name: Show Docker Compose logs
        run: |
          docker-compose logs
        working-directory: ./docker

        # Clean up after the services have been tested.
      - name: Clean up
        run: |
          docker-compose down
        working-directory: ./docker
